# Generated by Django 3.2.9 on 2021-12-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
